### ISSUE TITLE
ERROR or 118, 19

### ISSUE THREAD

**Issue by AFord7373** [KyroFrCode/moonlight-chrome-tizen#14]
Im using Linux Mint 21.2 Cinnamon 5.8.4

I have never used Linux and this is my first time, since I want to replace the steam link. Please be understanding.

Perhaps I installed docker incorrectly. I don't understand anything about this. If it's not difficult for you, give me instructions on how to do everything from the very beginning (starting with installing a new operating system)

1. when i try to download " docker build -t moonlight-tizen . " i have - 

aford@AFord-PC-Mint:~$ sudo docker build -t moonlight-tizen .
[+] Building 0.0s (2/2) FINISHED                                  docker:default
 => [internal] load build definition from Dockerfile                        0.0s
 => => transferring dockerfile: 2B                                          0.0s
 => [internal] load .dockerignore                                           0.0s
 => => transferring context: 2B                                             0.0s
ERROR: failed to solve: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount1161303933/Dockerfile: no such file or directory
(/var/lib/docker/tmp is empty)

IF I WILL NOT USE "SUDO" i will have this result - 

aford@AFord-PC-Mint:~$ docker build -t moonlight-tizen .
ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied

2. But then i try ti download "docker run -it --rm ghcr.io/kyrofrcode/moonlight-chrome-tizen:samsung_wasm" i have - 

ford@AFord-PC-Mint:~$ sudo docker run -it --rm ghcr.io/kyrofrcode/moonlight-chrome-tizen:samsung_wasm
Unable to find image 'ghcr.io/kyrofrcode/moonlight-chrome-tizen:samsung_wasm' locally
samsung_wasm: Pulling from kyrofrcode/moonlight-chrome-tizen
43f89b94cd7d: Pull complete 
72497b91ecd8: Downloading  314.3MB/427.4MB 72497b91ecd8: Downloading  319.7MB/427.4MB72497b91ecd8: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:7f0ff96ae15e95b561e626085ed59a0f5870688328220cd965ff7c2899078d3c
Status: Downloaded newer image for ghcr.io/kyrofrcode/moonlight-chrome-tizen:samsung_wasm

IF I WILL NOT USE "SUDO" i will have this result - 

aford@AFord-PC-Mint:~$ docker run -it --rm ghcr.io/kyrofrcode/moonlight-chrome-tizen:samsung_wasm
docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

2.1 then i can write "sdb connect YOUR_TV_IP" and have this - 

moonlight@0741bda0a9eb:~$ sdb connect 192.168.1.189
* Server is not running. Start it now on port 26099 *
* Server has started successfully *
connecting to 192.168.1.189:26101 ...
connected to 192.168.1.189:26101

2.3 If "sdb devices" i have - 

moonlight@0741bda0a9eb:~$ sdb devices
List of devices attached 
192.168.1.189:26101 	device    	UE43RU7097UXRU

2.4 And if i write "tizen install -n MoonlightWasm.wgt -t UE43RU7097UXRU" i have - 

moonlight@0741bda0a9eb:~$ tizen install -n MoonlightWasm.wgt -t UE43RU7097UXRU
Transferring the package...
Transferred the package: /home/moonlight/MoonlightWasm.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install MoonLightS.MoonlightWasm
package_path /home/owner/share/tmp/sdk_tools/tmp/MoonlightWasm.wgt
was_install_app return WAS_TRUE
app_id[MoonLightS.MoonlightWasm] install start
app_id[MoonLightS.MoonlightWasm] install failed[118, -19], reason: Parsing error : 
spend time for wascmd is [763]ms
cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:01.351

3. Also i havent any files in /home. Only my folder aford (/home/aford) so i cant edit config.xml couse i dont have it !!! 

Ask for any logs - I'll send them to you. Just please explain how to find them. I don't understand anything about Linux yet.
And yes, I fully restarted tv (pressed ON for 5 secs)
![Без названия](https://github.com/KyroFrCode/moonlight-chrome-tizen/assets/147619340/7a06ab39-f0f5-4a88-bc05-a38dd4008a0d)
![PXL_20231114_222316617](https://github.com/KyroFrCode/moonlight-chrome-tizen/assets/147619340/67e0e802-e2c3-4730-ae89-10a4d738916a)

**Comment by OneLiberty** [comment]
Hello,  

I'm having trouble finding any information about the os version that your tv is running, but based on [this ](https://www.samsung.com/us/support/answer/ANS00087664/) it seems that your tv model is from 2019 which suggest that it's running tizen 5.0 (https://developer.samsung.com/smarttv/develop/specifications/general-specifications.html). 
For now, the app is incompatible with tizen 5.0 or lower (and might forever be), hence why you can't install it. 

Issue similar to #8

**Comment by AFord7373** [comment]
Wow, thanks for such a quick response.  Yes, it looks like a 2019 release.  It is sad (

**Comment by AFord7373** [comment]
wow, thanks for such a quick response.  Yes, it looks like a 2019 release.  It is sad (
