### ISSUE TITLE
Unable to activate HDR stream on S90C

### ISSUE THREAD

**Issue by nkohler** [KyroFrCode/moonlight-chrome-tizen#19]
Hi!

First off, thank you for this awesome project. I've managed to get everything working fine, except for HDR. When running the client, game mode is activated as expected, but it runs it in SDR and (unsurprisingly) my colors are completely blown out. I've got a HDR compliant screen on my host computer with an RTX4090 and (as far as I can tell) Sunshine configured to enable an HDR stream.
![2023-11-22-display_hdr_settings](https://github.com/KyroFrCode/moonlight-chrome-tizen/assets/6176611/640fd3d1-fba3-40bb-a8da-810f717837b6)
![2023-11-22-sunshine_hdr_advertise](https://github.com/KyroFrCode/moonlight-chrome-tizen/assets/6176611/0a7b22a5-788a-48a5-96cb-dc761cd859ca)

Since HDR support is still marked as experimental, is it simply not included in this app?

TV: Samsung S90C
Host computer: RTX4090, Asus PG27AQDM, AMD Ryzen 7 7800X3D

Thanks again for what you do!

**Comment by OneLiberty** [comment]
By default it's not enabled in the app, i believe it causes some issue on some tvs (so it's disabled for compatibility reasons). 
You can re-enable it by uncommenting `//m_StreamConfig.enableHdr = true;` in `wasm/main.cpp` and build the app. 
I have no way of testing it as my computer display is not HDR capable, so it might not work

**Comment by Icedrow** [comment]
What about adding a toggle in app for testing purposes? Ideally the app should also switch between a SDR and an HDR video mode setting if HDR is enabled on host.

**Comment by nkohler** [comment]
Thank you! It's working fine on the S90C. Now I just have to figure out why some games stream buttery smooth and others less graphically intensive ones stutter around... Looking forwards to any improvements you guys make!

**Comment by Icedrow** [comment]
> Thank you! It's working fine on the S90C. Now I just have to figure out why some games stream buttery smooth and others less graphically intensive ones stutter around... Looking forwards to any improvements you guys make!

Check if you have borderless fullscreen enabled on game settings

**Comment by OneLiberty** [comment]
> > Thank you! It's working fine on the S90C. Now I just have to figure out why some games stream buttery smooth and others less graphically intensive ones stutter around... Looking forwards to any improvements you guys make!
> 
> Check if you have borderless fullscreen enabled on game settings

HAGS can cause issue as well, you can disable it in sunshine settings

**Comment by lion9994** [comment]
> By default it's not enabled in the app, i believe it causes some issue on some tvs (so it's disabled for compatibility reasons). You can re-enable it by uncommenting `//m_StreamConfig.enableHdr = true;` in `wasm/main.cpp` and build the app. I have no way of testing it as my computer display is not HDR capable, so it might not work

Where can i find "wasm/main.cpp"?
Thanks
