### ISSUE TITLE
Add Host Manually: Cannot select "CONTINUE"

### ISSUE THREAD

**Issue by crummy** [KyroFrCode/moonlight-chrome-tizen#26]
Using both the prebuilt Docker image and my own, I've managed to install the Moonlight app on my Samsung TV. However, when I use my remote to select Add Host, and enter my hostname in the Add Host Manually section, I'm unable to select Continue.

I've tried hooking up a mouse (no cursor) and hooking up a keyboard (think I managed to tab to Continue but ENTER did not do anything).

**Comment by OneLiberty** [comment]
try this [fork](https://github.com/OneLiberty/moonlight-chrome-tizen) : `docker run -it --rm ghcr.io/oneliberty/moonlight-chrome-tizen:samsung_wasm`

**Comment by crummy** [comment]
Thanks @OneLiberty . I had some odd issues where the IP address entry would be off-by-one (I'd select 192, then tap right on the remote to go to the next, and the box I'd just left would change to 193). But I adjusted my entries by -1 and everything worked fine. Appreciate it!

**Comment by OneLiberty** [comment]
Glad it worked ! 

Yeah, I don't know how to fix that, it occurs only with the remote, not the gamepad.

So I strongly suggest using the gamepad or switching to the input field for the keyboard
