### ISSUE TITLE
Remote control volume 

### ISSUE THREAD

**Issue by andres-torti** [KyroFrCode/moonlight-chrome-tizen#3]
Hi! THANK YOU for this, it works wonderfully. The only thing I noticed is I cannot control the TV volume using the remote control, do you know where the code should be modified to allow for it? I can work on it and make a PR

**Comment by henryfa2** [comment]
Hey, I can confirm I got same issue on my Samsung QE55Q83B TV.

**Comment by andres-torti** [comment]
I think I found the solution, I will be making a PR with this fix and other small fixes

**Comment by dragondgold** [comment]
@henryfa2 just made a PR, give it a try to see if it works for you

**Comment by henryfa2** [comment]
I'll test it when I am home.
Do you know if I have to reconfigure everything after reinstalling the app? (It is first time I install / reinstall an app on my TV)

**Comment by dragondgold** [comment]
No need to reconfigure anything, just install the app again and it will we updated, all settings will be kept

**Comment by henryfa2** [comment]
All right, I tested your PR @dragondgold : 

- Fix elements not having hover styles when using a controller : Working well, so nice :D
- Allow changing volume from remote control (fixes Remote control volume  #3) : Working but seems like it sends weird keys to host computer (volume up is like "!" key and volume down is like "²" key). No clue if I had this behaviour before the update though.
- stop streaming with controller by pressing start+menu+left trig… : Working but that do not stop the "streaming mode" on host computer, is that intended? If so, maybe it would be a good thing to be able to stop the "streaming mode" on computer and close the connection if we press Start + Menu + LT + RT for example.

Thanks for your work :)

**Comment by dragondgold** [comment]
> - Allow changing volume from remote control (fixes Remote control volume  #3) : Working but seems like it sends weird keys to host computer (volume up is like "!" key and volume down is like "²" key). No clue if I had this behaviour before the update though.

That's weird, I didn't noticed it in my PC but will double check it. What TV do you have? My TV changes volume but it doesn't show the UI when it changes. 

> - stop streaming with controller by pressing start+menu+left trig… : Working but that do not stop the "streaming mode" on host computer, is that intended? If so, maybe it would be a good thing to be able to stop the "streaming mode" on computer and close the connection if we press Start + Menu + LT + RT for example.

Yes, unfortunately I don't know how to stop the streaming on the host side. From what I read there's nothing on the GeForce experience side to stop it.

**Comment by henryfa2** [comment]
> > * stop streaming with controller by pressing start+menu+left trig… : Working but that do not stop the "streaming mode" on host computer, is that intended? If so, maybe it would be a good thing to be able to stop the "streaming mode" on computer and close the connection if we press Start + Menu + LT + RT for example.
> 
> Yes, unfortunately I don't know how to stop the streaming on the host side. From what I read there's nothing on the GeForce experience side to stop it.

I think the function stopGame in index.js might be an example of how to quit the app on host computer?
